{% set version = "1.21.10" %}

package:
  name: conda-build
  version: {{ version }}

source:
  fn: conda-build-{{ version }}.tar.gz
  url: https://github.com/conda/conda-build/archive/{{ version }}.tar.gz
  sha256: 3a0bbf2c3ed3db08b85a3ae233754fa4c943fb420bd60b5386ee79d773f231d4

build:
  number: 0
  script:
    # IMPORTANT: this is not conda-forge standard, but it is essential to install entry point scripts
    #    that do not use eggs.
    - pip install --no-deps .
    - cp bdist_conda.py ${PREFIX}/lib/python${PY_VER}/distutils/command  # [unix]
    - copy bdist_conda.py %PREFIX%\Lib\distutils\command\  # [win]

requirements:
  build:
    - python
    - pip

  run:
    - conda >=4.1
    - jinja2
    - patch         # [win]
    - patchelf      # [linux]
    - pycrypto
    - python
    - pyyaml

test:
  imports:
    - conda_build

  commands:
    - which conda-build  # [unix]
    - where conda-build  # [win]
    - conda build -h
    - which conda-convert  # [unix]
    - where conda-convert  # [win]
    - conda convert -h
    - which conda-develop  # [unix]
    - where conda-develop  # [win]
    - conda develop -h
    - which conda-index  # [unix]
    - where conda-index  # [win]
    - conda index -h
    - which conda-inspect  # [unix]
    - where conda-inspect  # [win]
    - conda inspect -h
    - conda inspect linkages -h \| grep "--name ENVIRONMENT"  # [unix]
    - conda inspect objects -h \| grep "--name ENVIRONMENT"   # [osx]
    - which conda-metapackage  # [unix]
    - where conda-metapackage  # [win]
    - conda metapackage -h
    - which conda-pipbuild  # [unix]
    - where conda-pipbuild  # [win]
    - conda pipbuild -h
    - which conda-render  # [unix]
    - where conda-render  # [win]
    - conda render -h
    - which conda-sign  # [unix]
    - where conda-sign  # [win]
    - conda sign -h
    - which conda-skeleton  # [unix]
    - where conda-skeleton  # [win]
    - conda skeleton -h

about:
  home: https://github.com/conda/conda-build
  summary: tools for building conda packages
  license: BSD 3-Clause

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
