{% set version = "2.1.5" %}

package:
  name: conda-build
  version: {{ version }}

source:
  fn: conda-build-{{ version }}.tar.gz
  url: https://github.com/conda/conda-build/archive/{{ version }}.tar.gz
  sha256: 8bee3ee7d7053f32c4e465aeb55f66f58440e5a2c7178a4393f4238cec141e5d

build:
  number: 1
  entry_points:
    - conda-build = conda_build.cli.main_build:main
    - conda-convert = conda_build.cli.main_convert:main
    - conda-develop = conda_build.cli.main_develop:main
    - conda-index = conda_build.cli.main_index:main
    - conda-inspect = conda_build.cli.main_inspect:main
    - conda-metapackage = conda_build.cli.main_metapackage:main
    - conda-render = conda_build.cli.main_render:main
    - conda-sign = conda_build.cli.main_sign:main
    - conda-skeleton = conda_build.cli.main_skeleton:main

requirements:
  build:
    - python
    - setuptools

  run:
    - beautifulsoup4
    - chardet
    - conda  >=4.1
    - contextlib2        # [py27]
    - conda-verify
    - enum34             # [py27]
    - filelock
    - futures            # [py27]
    - jinja2
    - patchelf           # [linux]
    - pkginfo
    - pycrypto
    - python
    - pyyaml
    - six

test:
  # If you run the test suite (~10 min), these are required
  # requires:
  #   - pytest
  #   - pytest-timeout
  #   - pytest-catchlog

  files:
    - test_bdist_conda_setup.py

  imports:
    - conda_build

  commands:
    # Check for all subcommands
    - which conda-build  # [unix]
    - where conda-build  # [win]
    - conda-build -h
    - which conda-convert  # [unix]
    - where conda-convert  # [win]
    - conda-convert -h
    - which conda-develop  # [unix]
    - where conda-develop  # [win]
    - conda-develop -h
    - which conda-index  # [unix]
    - where conda-index  # [win]
    - conda-index -h
    - which conda-inspect  # [unix]
    - where conda-inspect  # [win]
    - conda-inspect linkages -h \| grep "--name ENVIRONMENT"  # [unix]
    - conda-inspect objects -h \| grep "--name ENVIRONMENT"   # [osx]
    - conda-inspect -h
    - which conda-metapackage  # [unix]
    - where conda-metapackage  # [win]
    - conda-metapackage -h
    - which conda-render  # [unix]
    - where conda-render  # [win]
    - conda-render -h
    - which conda-sign  # [unix]
    - where conda-sign  # [win]
    - conda-sign -h
    - which conda-skeleton  # [unix]
    - where conda-skeleton  # [win]
    - conda-skeleton -h

    # Check for bdist_conda
    - python test_bdist_conda_setup.py bdist_conda --help

about:
  home: https://github.com/conda/conda-build
  summary: tools for building conda packages
  license: BSD 3-Clause

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
