build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  linux_ppc64le: default
remote_ci_setup:
  - conda-build>=3.23.2
  - conda-forge-ci-setup=3
  - py-lief>=0.12.3
test_on_native_only: true
conda_build:
  pkg_format: '2'
